# Generated by Django 6.0 on 2026-01-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_status_delete_orderaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_price_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount paid for this item (used for refunds)', max_digits=10),
            preserve_default=False,
        ),
    ]
