# Generated by Django 6.0 on 2026-01-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
