# Generated by Django 6.0 on 2026-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment_address_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay'), ('wallet', 'Wallet')], default='cod', max_length=20),
        ),
    ]
