# Generated by Django 6.0 on 2026-01-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
