# Generated by Django 6.0 on 2026-01-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_payment_uuid_returnrequest_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
