# Generated by Django 6.0 on 2026-01-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_add_returnrequest_uuid_column'),
    ]

    operations = [
    ]
