# Generated by Django 6.0 on 2026-01-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_options_alter_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='SiteBanner',
        ),
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'ordering': ['-created_at']},
        ),
    ]
