# Generated by Django 6.0 on 2026-01-30 09:17

import uuid
from django.db import migrations, models




def populate_coupon_uuids(apps, schema_editor):
    Coupon = apps.get_model("coupons", "Coupon")
    for coupon in Coupon.objects.all():
        coupon.uuid = uuid.uuid4()
        coupon.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_couponusage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(populate_coupon_uuids),
        migrations.AlterField(
            model_name='coupon',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

