# Generated by Django 6.0 on 2026-01-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment_address_snapshot'),
        ('wallet', '0002_adminwallet_adminwallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('txn_type', 'credit')), fields=('order_item',), name='unique_refund_per_order_item'),
        ),
    ]
