# Generated by Django 6.0 on 2026-01-15 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_method'),
        ('wallet', '0003_wallettransaction_order_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminwallettransaction',
            options={},
        ),
        migrations.AddConstraint(
            model_name='adminwallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'credit')), fields=('order',), name='unique_admin_credit_per_order'),
        ),
    ]
