# Generated by Django 6.0 on 2026-01-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_productreview_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(blank=True),
        ),
    ]
