# Generated by Django 6.0 on 2026-01-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='Land_mark',
            new_name='land_mark',
        ),
    ]
