# Generated by Django 6.0 on 2026-01-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'created_at'], name='accounts_em_email_adc4a4_idx'),
        ),
    ]
