# Generated by Django 6.0 on 2025-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
