# Generated by Django 6.0 on 2026-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp_accounts_em_email_adc4a4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset', 'Password Reset'), ('email_change', 'Email Change')], max_length=12),
        ),
    ]
