# Generated by Django 6.0 on 2025-12-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
    ]
