# Generated by Django 6.0 on 2026-01-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productvariant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
