# Generated by Django 6.0 on 2026-01-01 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
